import { AfterViewInit, ChangeDetectorRef, ElementRef, EventEmitter, QueryList } from '@angular/core';
import { BaseObject, ObservableValue } from 'mrd-core';
import { MrdTabBodyComponent } from '../../../mrd-tabs/components/mrd-tab-body/mrd-tab-body.component';
import { MrdStepComponent } from '../mrd-step/mrd-step.component';
import { ActivatedRoute, Router } from '@angular/router';
import * as i0 from "@angular/core";
export declare class MrdStepperComponent extends BaseObject implements AfterViewInit {
    private cdr;
    private router;
    private route;
    steps: QueryList<MrdStepComponent>;
    stepBodys: QueryList<MrdTabBodyComponent>;
    stepHeader: QueryList<ElementRef>;
    set headerHeight(value: number);
    get headerHeight(): number;
    private _headerHeight;
    set selectedIndex(value: number);
    get selectedIndex(): number;
    private _selectedIndex;
    changeStep: ObservableValue<number>;
    linear: boolean;
    selectedStepChanged: EventEmitter<MrdStepComponent>;
    selectedStepIndexChanged: EventEmitter<number>;
    activeIndex: number;
    private activeStep;
    private activeStepBody;
    constructor(cdr: ChangeDetectorRef, router: Router, route: ActivatedRoute);
    ngAfterViewInit(): void;
    activateStep(index: number): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<MrdStepperComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<MrdStepperComponent, "mrd-stepper", never, { "headerHeight": { "alias": "headerHeight"; "required": false; }; "selectedIndex": { "alias": "selectedIndex"; "required": false; }; "changeStep": { "alias": "changeStep"; "required": false; }; "linear": { "alias": "linear"; "required": false; }; }, { "selectedStepChanged": "selectedStepChanged"; "selectedStepIndexChanged": "selectedStepIndexChanged"; }, ["steps"], never, false, never>;
    static ngAcceptInputType_linear: unknown;
}
