import { AfterViewInit, ChangeDetectorRef, OnDestroy } from '@angular/core';
import { MrdInputComponent } from '../mrd-input/mrd-input.component';
import { MrdLabelComponent } from '../mrd-label/mrd-label.component';
import { BaseObject } from 'mrd-core';
import { MrdErrorComponent } from '../mrd-error/mrd-error.component';
import { MrdSelectComponent } from '../mrd-select/mrd-select.component';
import * as i0 from "@angular/core";
export declare class MrdFormFieldComponent extends BaseObject implements AfterViewInit, OnDestroy {
    private cdr;
    private config;
    input: MrdInputComponent;
    select: MrdSelectComponent;
    label: MrdLabelComponent;
    error: MrdErrorComponent;
    outline: boolean;
    fill: boolean;
    dark: boolean;
    requiredAsterisk: boolean;
    rounded: boolean;
    borderRadius: string;
    centered: boolean;
    textEnd: boolean;
    fillColor: string;
    disabled: boolean;
    focused: boolean;
    hasError: boolean;
    focusColor: string;
    focusColorDark: string;
    focusColorOutline: string;
    errorColor: string;
    errorColorDark: string;
    errorColorOutline: string;
    private timeouts;
    constructor(cdr: ChangeDetectorRef);
    ngOnDestroy(): void;
    ngAfterViewInit(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<MrdFormFieldComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<MrdFormFieldComponent, "mrd-form-field", never, { "outline": { "alias": "outline"; "required": false; }; "fill": { "alias": "fill"; "required": false; }; "dark": { "alias": "dark"; "required": false; }; "requiredAsterisk": { "alias": "requiredAsterisk"; "required": false; }; "rounded": { "alias": "rounded"; "required": false; }; "borderRadius": { "alias": "borderRadius"; "required": false; }; "centered": { "alias": "text-centered"; "required": false; }; "textEnd": { "alias": "text-end"; "required": false; }; "fillColor": { "alias": "fillColor"; "required": false; }; }, {}, ["input", "select", "label", "error"], ["mrd-prefix", "mrd-input", "mrd-select", "mrd-label", "mrd-suffix", "mrd-hint", "mrd-error"], false, never>;
    static ngAcceptInputType_outline: unknown;
    static ngAcceptInputType_fill: unknown;
    static ngAcceptInputType_dark: unknown;
    static ngAcceptInputType_rounded: unknown;
    static ngAcceptInputType_borderRadius: string | number;
    static ngAcceptInputType_centered: unknown;
    static ngAcceptInputType_textEnd: unknown;
    static ngAcceptInputType_fillColor: string;
}
