import { ChangeDetectorRef, EventEmitter, OnInit } from '@angular/core';
import { MrdToggleSwitchState } from '../../common/enum/mrd-toggle-switch-state.enum';
import * as i0 from "@angular/core";
export declare class MrdToggleSwitchComponent implements OnInit {
    private cdr;
    MrdToggleSwitchState: typeof MrdToggleSwitchState;
    bgColor: string;
    bgNeutralColor: string;
    knobColor: string;
    knobNeutralColor: string;
    width: string;
    height: string;
    bgDisabledColor: string;
    knobDisabledColor: string;
    disabled: boolean;
    set state(value: MrdToggleSwitchState);
    get state(): MrdToggleSwitchState;
    private _state;
    stateChange: EventEmitter<MrdToggleSwitchState>;
    private _config;
    constructor(cdr: ChangeDetectorRef);
    ngOnInit(): void;
    toggle(event: PointerEvent, state?: MrdToggleSwitchState): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<MrdToggleSwitchComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<MrdToggleSwitchComponent, "mrd-toggle-switch", never, { "bgColor": { "alias": "bgColor"; "required": false; }; "bgNeutralColor": { "alias": "bgNeutralColor"; "required": false; }; "knobColor": { "alias": "knobColor"; "required": false; }; "knobNeutralColor": { "alias": "knobNeutralColor"; "required": false; }; "width": { "alias": "width"; "required": false; }; "height": { "alias": "height"; "required": false; }; "bgDisabledColor": { "alias": "bgDisabledColor"; "required": false; }; "knobDisabledColor": { "alias": "knobDisabledColor"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "state": { "alias": "state"; "required": false; }; }, { "stateChange": "stateChange"; }, never, never, false, never>;
    static ngAcceptInputType_bgColor: string;
    static ngAcceptInputType_bgNeutralColor: string;
    static ngAcceptInputType_knobColor: string;
    static ngAcceptInputType_knobNeutralColor: string;
    static ngAcceptInputType_width: string | number;
    static ngAcceptInputType_height: string | number;
    static ngAcceptInputType_bgDisabledColor: string;
    static ngAcceptInputType_knobDisabledColor: string;
    static ngAcceptInputType_disabled: unknown;
}
