import { ObservableValue } from 'mrd-core';
import { AfterViewInit, ChangeDetectorRef, OnInit } from '@angular/core';
import * as i0 from "@angular/core";
export declare class MrdButtonComponent implements OnInit, AfterViewInit {
    private cdr;
    icon: boolean;
    raised: boolean;
    outline: boolean;
    flat: boolean;
    fab: boolean;
    miniFab: boolean;
    set primary(value: boolean);
    get primary(): boolean;
    private _primary;
    set accent(value: boolean);
    get accent(): boolean;
    private _accent;
    set warn(value: boolean);
    get warn(): boolean;
    private _warn;
    set disabled(value: boolean);
    get disabled(): boolean;
    private _disabled;
    loading: ObservableValue<boolean>;
    private _config;
    private _defaultBgColor;
    private _defaultTextLightColor;
    private _defaultTextDarkColor;
    private _defaultHoverColor;
    private _defaultActiveColor;
    private _defaultDisabledTextColor;
    private _defaultDisabledBgColor;
    private _defaultOutlineBorderWidth;
    private _defaultOutlineBorderStyle;
    private _defaultOutlineBorderColor;
    bgColor: string;
    private textLightColor;
    private textDarkColor;
    textColor: string;
    hoverColor: string;
    activeColor: string;
    disabledTextColor: string;
    disabledBgColor: string;
    outlineBorderWidth: string;
    outlineBorderStyle: string;
    outlineBorderColor: string;
    constructor(cdr: ChangeDetectorRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<MrdButtonComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<MrdButtonComponent, "mrd-button", never, { "icon": { "alias": "icon-button"; "required": false; }; "raised": { "alias": "raised-button"; "required": false; }; "outline": { "alias": "outline-button"; "required": false; }; "flat": { "alias": "flat-button"; "required": false; }; "fab": { "alias": "fab-button"; "required": false; }; "miniFab": { "alias": "miniFab-button"; "required": false; }; "primary": { "alias": "primary"; "required": false; }; "accent": { "alias": "accent"; "required": false; }; "warn": { "alias": "warn"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "loading": { "alias": "loading"; "required": false; }; }, {}, never, ["*"], false, never>;
    static ngAcceptInputType_icon: unknown;
    static ngAcceptInputType_raised: unknown;
    static ngAcceptInputType_outline: unknown;
    static ngAcceptInputType_flat: unknown;
    static ngAcceptInputType_fab: unknown;
    static ngAcceptInputType_miniFab: unknown;
    static ngAcceptInputType_primary: unknown;
    static ngAcceptInputType_accent: unknown;
    static ngAcceptInputType_warn: unknown;
    static ngAcceptInputType_disabled: unknown;
}
