import { ChangeDetectorRef } from '@angular/core';
import * as i0 from "@angular/core";
export declare class MrdDecimalComponent {
    private cdr;
    set backgroundColor(value: string);
    get backgroundColor(): string;
    private _backgroundColor;
    set color(value: string);
    get color(): string;
    private _color;
    set textEnd(value: boolean);
    get textEnd(): boolean;
    private _textEnd;
    set centered(value: boolean);
    get centered(): boolean;
    private _centered;
    set value(value: number);
    get value(): number;
    private _value;
    set maxDigits(value: number);
    get maxDigits(): number;
    private _maxDigits;
    set minDigits(value: number);
    get minDigits(): number;
    private _minDigits;
    set tausendertrennpunkt(value: boolean);
    get tausendertrennpunkt(): boolean;
    private _tausendertrennpunkt;
    smallDigits: boolean;
    private decimalString;
    private digitsString;
    constructor(cdr: ChangeDetectorRef);
    get decimalValue(): string;
    get digitsValue(): string;
    private generateValueString;
    static ɵfac: i0.ɵɵFactoryDeclaration<MrdDecimalComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<MrdDecimalComponent, "mrd-decimal", never, { "backgroundColor": { "alias": "backgroundColor"; "required": false; }; "color": { "alias": "color"; "required": false; }; "textEnd": { "alias": "text-end"; "required": false; }; "centered": { "alias": "text-centered"; "required": false; }; "value": { "alias": "value"; "required": false; }; "maxDigits": { "alias": "maxDigits"; "required": false; }; "minDigits": { "alias": "minDigits"; "required": false; }; "tausendertrennpunkt": { "alias": "tausendertrennpunkt"; "required": false; }; "smallDigits": { "alias": "smallDigits"; "required": false; }; }, {}, never, never, false, never>;
    static ngAcceptInputType_textEnd: unknown;
    static ngAcceptInputType_centered: unknown;
    static ngAcceptInputType_maxDigits: unknown;
    static ngAcceptInputType_minDigits: unknown;
    static ngAcceptInputType_tausendertrennpunkt: unknown;
    static ngAcceptInputType_smallDigits: unknown;
}
